import type { Metadata } from "next";
import "./globals.css";
import { getServerAuthSession } from "@/server/auth";
import Dashboard from "@/components/Dashboard";
import useFonts from "@/hooks/useFonts";

export const metadata: Metadata = {
  title: "Stack me",
  description: "Generated by create next app",
};

export default async function RootLayout(props: {
  children: React.ReactNode;
  login: React.ReactNode;
  modal: React.ReactNode;
}) {
  const session = await getServerAuthSession();
  const { Jim, poppins } = useFonts();

  if (!session) {
    return (
      <html lang='en'>
        <body className={Jim.className}>{props.login}</body>
      </html>
    );
  }
  return (
    <html lang='en'>
      <body className={`flex ${Jim.className}`}>
        <Dashboard session={session} />
        <div className={` ${poppins.className} flex-1`}>{props.children}</div>
      </body>
    </html>
  );
}
